blargbot/blargbot

worker.js
=> Better clyde, better life

src/tags/if.js
Added support for `{if;bool;then}`
Added error message when the 1st argument of a short if statement is not true/false or equivalent
Added error message when too many arguments are supplied to the tag
=> Tweak to If tag

src/tags/for.js, src/tags/foreach.js
Plz cat i will love you long time <3
(I know it almost certainly wont work first time, if only I were able to debug...)
=> Added for and foreach tags

Production/Commands/general/mods.js, Prototypes.js
The car ride was long and boring.
=> Add name escaping and address a Trello issue

README.MD
**Heya cat!**
Blargbot is featured on the [Awesome Discord](https://github.com/jacc/awesome-discord) repository. 
This project is a part of the "Awesome" network created by sindresorhus. You can read more about [what is an awesome list](https://github.com/sindresorhus/awesome/blob/master/awesome.md) if you're a ~~stupid~~ curious cat. 
For this very reason, we suggest that you add the "Mentioned in Awesome" badge to your repository. It's a cool way to share the awesome list with other peoples, and it would greatly help us. :octocat:
=> Added "Mentioned in Awesome" badge.

src/backend/helpers.js, src/core/tags.js, src/dcommands/help.js, src/tags/bool.js, src/tags/dm.js, src/tags/edit.js, src/tags/embed.js, src/tags/randchoose.js, src/tags/send.js, src/tags/sort.js
Fixes for negative number comparison. I know its not ideal but its the best I could think of ;-;
Fix some other small issues.
Enable embeds in DM's
=> Bbtag update phase1 patch

src/tags/usernick.js
Not sure on why this errors, but sometimes it does. This should fix it
=> Usernick fix

src/backend/routes/tags.js, src/core/discord.js, src/structures/ArgumentFactory.js
For my bbtag extension for vscode, im intending to add a lot of help information. Being able to access the live definitions from blargbot would be incredibly useful, so I thought adding a json endpoint would be useful.
The endpoint is `/tags/json`
=> Add tag defintions endpoint

src/dcommands/ccommand.js, src/dcommands/tag.js, src/dcommands/timers.js, src/events/guildCreate.js
1) added the info subcommand to `timers` (aliases : raw, content) which outputs the content of the timer.
Syntax: `b!timer info <id>`
2) adapted the first message of the bot (when it gets in a guild)
3) adapted cc and tag messages (please add support for subcommands to BaseCommand)
4) added the author subcommand to `ccommand`
=> blabla ez work

src/backend/public/css/main.css, src/backend/views/variables.hbs
Let's move from this old ugly shitty look 
to the new and beautiful one for more clarity and fun!
Note : I'm sorry I had to test it on a local file... Please REVIEW and move the shit out of the file! @Ratismal
=> A new table for "variables" page!

src/dcommands/ccommand.js, src/dcommands/tag.js
=> A few display edits

src/backend/views/partials/sidebar.hbs
Fixing an issue where a user without a custom avatar doesn't have any image loaded when connected
=> User avatar not loaded

src/dcommands/shard.js
Not important, but small copy-paste error.
=> Change class name for shard command

src/dcommands/remind.js
=> Add check for remind text

src/dcommands/kick.js
https://discord.com/channels/194232473931087872/238131984017260546/719352256071467038
=> Fix the reason message containing commas

src/dcommands/ban.js
Changed the constructor info to 1 day as the function says it's 1 day.
=> Change info default days to 1, matching the function

src/dcommands/timezone.js
time & timezone are two different built-in commands.
=> Fix misleading usage

src/dcommands/censor.js
Added missing documentation of `b!censor edit` as it's not obvious `censor` supports it
=> Added documentation of the edit subcommand for censors

src/tags/flags.js, src/tags/flagsarray.js
New flagsarray subtag to display an array of flags provided. This includes flags without value.
In response to suggestion [682](https://airtable.com/shrEUdEv4NM04Wi7O/tblyFuWE6fEAbaOfo/viwWwUA753iEQqOo7/recN3eXc0EUub13mF?blocks=bipip3uBZFRPcSy3C)
**Added**:
- {flagsarray} [d100a19](https://github.com/blargbot/blargbot/commit/d100a19b24cd237208f120c338de1809755fe3ce)
=> New flagsarray subtag

package.json, src/core/discord.js
Use Date.now() rather than new Date()
Update pg to 8.5.0. Tested locally and it still works with both a local postgres and blargbots postgres
=> Fix NaN in down detection

src/dcommands/help.js
Changed the order of checking the argument from default command then custom command, to custom command then default command.
Fixes bug report [728](https://airtable.com/shrEUdEv4NM04Wi7O/tblyFuWE6fEAbaOfo/viwDg5WovcwMA9NIL/recaBJMuEGz0MOqoY?blocks=bipip3uBZFRPcSy3C)
**Changed**:
- Order of if else [ 16b3a5d ](https://github.com/blargbot/blargbot/commit/16b3a5df1f0a52bd3aeb5d219d59f607a3cc7825)
=> Fixed default help being displayed when a custom help exists

src/structures/bbtag/Context.js
Improve the await stack (maybe) and fix undefined error for timers that are using a channel
=> Improve context.js error avoidance

src/core/Spawner.js, src/structures/Shard.js
Something is causing clusters to stop talking to the master process, hopefully this will log when that happens.
Also add links fix to ignore when ready is fired multiple times.
[Discord discussion](https://discord.com/channels/194232473931087872/604763099727134750/857269553012015154)
=> Log other childprocess events as errors

src/backend/helpers.js
Not sure if this will fix all the issues, but hopefully will fix the current one. Cant reproduce it locally
=> Add some undef checks for tags rendering

src/dcommands/censor.js
=> Dont keep looping after censor limit is hit

src/core/Metrics.ts, src/workers/cluster/bbtag/BaseSubtag.ts
Copy of PR https://github.com/blargbot/blargbot/pull/305 but in TS
=> [TS] Added subtag counter metric

src/dcommands/kick.js
**Changed**
- Join the reason with a space as a string in case it is an array 421495a
=> fix: properly format reason

package.json, src/workers/cluster/Cluster.ts, src/workers/cluster/dcommands/developer/patch.ts, src/workers/cluster/dcommands/developer/update.ts, src/workers/cluster/dcommands/general/stats.ts, src/workers/cluster/dcommands/general/version.ts, src/workers/cluster/managers/VersionStateManager.ts, src/workers/cluster/managers/index.ts, yarn.lock
- Adds a `VersionStateManager` to encapsulate the logic of retrieving, parsing and updating the version from/to the database.
- Updates the related default commands to use it as well.
=> VersionStateManager

src/tags/exec.js, src/tags/execcc.js
This reverts commit 650651901c3fb6a65c8364e99f4de45568b40151.
=> Revert "Fix exec and execcc"

src/tags/exec.js, src/tags/execcc.js, src/tags/inject.js
=> Revert "Bugs/fix exec escapes"

src/tags/exec.js, src/tags/execcc.js, src/tags/inject.js
=> Revert "Features/exec escape"

src/dcommands/mods.js, src/events/ready.js, src/tags/guildmembers.js, src/tags/randuser.js, src/tags/rolesize.js, src/utils/generic.js
Add a mechanism to lazily request all guild members, to ensure the cache is fully populated
=> Add ensureMembers method

src/core/utils/parse/parseFloat.ts, src/core/utils/parse/parseInt.ts
=> Allow parseint/parsefloat to use negative numbers

src/bbtag/BBTagContext.ts, src/cluster/managers/moderation/ChatLogManager.ts, src/cluster/start.ts, src/logger/createLogger.ts
- Fixes sentry logging errors with title `sendToSentry`. Now has a more meaningful error
- Fixes [#BLARGBOT-375](https://sentry.blargbot.xyz/organizations/blargbot/issues/3313)
- Fixes [#BLARGBOT-37B](https://sentry.blargbot.xyz/organizations/blargbot/issues/3319)
=> Fix some sentry errors

src/core/BaseUtilities.ts
Fixes [b!log ignore isnt working](https://discord.com/channels/194232473931087872/989535097533366322)
=> querying senders should persist query to member/webhook

src/cluster/managers/moderation/BanManager.ts
Fixes [Modlog shows blargbot as moderator on manual kick](https://discord.com/channels/194232473931087872/987516388417605662)
=> Log kicks using correct moderator

src/bbtag/subtags/bot/args.ts, src/bbtag/subtags/bot/params.ts, test/bbtag/subtags/bot/args.test.ts, test/bbtag/subtags/bot/params.test.ts
Fixes [expected 1 arguments or more but got 1](https://discord.com/channels/194232473931087872/989592545417900162)
=> {args} and {params} debug message fix

src/cluster/managers/moderation/BanManager.ts
Actually fixes [Modlog shows blargbot as moderator on manual kick](https://discord.com/channels/194232473931087872/987516388417605662)
#349 missed this somehow
=> Actually fix kicks having incorrect moderator

src/cluster/dcommands/admin/ccommand.ts
Fixes [shrinkwrap install doesnt seem to work](https://discord.com/channels/194232473931087872/989337953581015050)
=> Fix shrinkwrapping

src/cluster/managers/moderation/EventLogManager.ts, src/database/stores/RethinkDbGuildStore.ts
Fixes [Message delete logs often times do not properly get the author's username and discrim](https://discord.com/channels/194232473931087872/989345216442007582) and an issue I spotted where `b!log track <sender>` didnt work
=> Message delete event missing some author information

src/bbtag/BBTagContext.ts
If a user has left the guild, still run any bbtag timers they triggered
Fixes [[Bug] Timers not working if user left guild](https://discord.com/channels/194232473931087872/995088676382056459)
=> Allow timers where user left the server

src/cluster/Cluster.ts, src/cluster/events/discord/guildCreate.ts, src/cluster/events/discord/guildDelete.ts, src/cluster/events/discord/ready.ts, src/cluster/managers/GuildManager.ts, src/cluster/managers/index.ts
Hopefully fixes an issue where guilds dont have a record in the DB
=> Centralize guild loading & remove hello message

src/cluster/dcommands/general/timezone.ts
Add a link to the list of allowed timezones with the timezone command help
=> Update timezone documentation

src/cluster/Cluster.ts, src/cluster/events/discord/guildCreate.ts, src/cluster/events/discord/guildDelete.ts, src/cluster/events/discord/ready.ts, src/cluster/managers/GuildManager.ts, src/cluster/managers/index.ts
Hopefully fixes an OOM issue introduced by #361
=> Centralize guild loading & remove hello message 2.0

src/cluster/dcommands/admin/censor.ts
Fixes [BLARGBOT-3RF](https://sentry.blargbot.xyz/organizations/blargbot/issues/3870/?project=2)
=> Fix command arg being incorrectly read

src/bbtag/subtags/array/filter.ts, test/bbtag/subtags/array/filter.test.ts
Fixes [broken {filter}](https://discord.com/channels/194232473931087872/1003000055663427704)
=> Filter should trim arg before parsing

src/cluster/Cluster.ts, src/cluster/dcommands/admin/announce.ts, src/cluster/dcommands/general/poll.ts, src/cluster/managers/AnnouncementManager.ts, src/cluster/managers/PollManager.ts, src/cluster/managers/index.ts, src/cluster/types.ts
Fixes [poll command does not work when '-a' or '--announce' flag used](https://discord.com/channels/194232473931087872/989132399155748884)
=> Implement poll announcements

src/cluster/dcommands/admin/ban.ts
Implements the change requested here: [b!ban doesnt work with userids if the user isnt in the guild](https://discord.com/channels/194232473931087872/1009354648928403467)
=> User doesnt have to be in the guild to ban them

src/database/stores/CassandraDbChatLogStore.ts
Fixes [b!logs is prone to breaking for no apparent reason](https://discord.com/channels/194232473931087872/1007028175013937152)
=> Split chatlog retrieval into batches

src/core/utils/humanize/smartSplit.ts
=> end is max not min

src/api/routes/tags.ts, src/cluster/dcommands/general/feedback.ts, src/cluster/dcommands/general/tag.ts
=> Allow police to moderate tags and feedback

src/cluster/managers/commands/DefaultCommandManager.ts
Default command permissions (from their category) should only be applied if the command hasnt had any roles/permissions set by editcommand
Related to #388
=> ignore default command permissions after editing

src/core/utils/humanize/smartSplit.ts, test/bbtag/subtags/bot/exec.test.ts, test/bbtag/subtags/bot/execcc.test.ts
Fixes [Json funkiness in {exec}](https://discord.com/channels/194232473931087872/1015443632834220032)
=> Fix smartsplit with escapes inside quote

src/cluster/managers/moderation/EventLogManager.ts
=> Don't repeat channel on bulk delete

src/database/stores/CassandraDbChatLogStore.ts
Fixes [b!logs is prone to breaking for no apparent reason](https://discord.com/channels/194232473931087872/1019673874222305302)
I should have read the [documentation...](https://docs.datastax.com/en/developer/nodejs-driver/4.6/features/paging/#automatic-paging)
=> Fix logs not checking further pages

src/cluster/events/discord/messageCreate.ts, src/cluster/events/discord/messageUpdate.ts
Implements [Slash commands which defer responses dont trigger autoresponses](https://discord.com/channels/194232473931087872/1019673668265181275)
=> Correctly handle system updates to messages and command messages

src/cluster/events/discord/messageUpdate.ts, src/cluster/events/discord/middleware/CensorMiddleware.ts, src/cluster/managers/moderation/CensorManager.ts, src/core/utils/guard/matchMessageFilter.ts
Fixes [Censors dont trigger on updates](https://discord.com/channels/194232473931087872/1019956875942449162)
=> Execute censors on message update

src/bbtag/BBTagContext.ts, src/bbtag/subtags/bot/prefix.ts, src/bbtag/types.ts, src/cluster/dcommands/admin/ccommand.ts, src/cluster/dcommands/general/tag.ts, src/cluster/managers/commands/CustomCommandManager.ts, test/bbtag/subtags/bot/prefix.test.ts
Implements [{prefix} should return the prefix used, if available](https://discord.com/channels/194232473931087872/1019673263296761876)
=> Make prefix subtag return the prefix that was used, if available

src/api/routes/chatLogs.ts, src/api/routes/dumps.ts, src/core/BaseUtilities.ts, src/domain/models/Dump.ts, src/domain/models/chatLogs/index.ts, src/domain/models/discordTags/DiscordChannelTag.ts, src/domain/models/discordTags/DiscordRoleTag.ts, src/domain/models/discordTags/DiscordTagSet.ts, src/domain/models/discordTags/DiscordUserTag.ts, src/domain/models/discordTags/index.ts, src/domain/models/index.ts
Bulk of the changes are from moving the tag resolution logic from the chatlogs api into the common area to be reused by dumps
=> Support mentions in dumps

src/cluster/dcommands/admin/autoresponse.ts, src/cluster/dcommands/admin/ccommand.ts, src/cluster/dcommands/admin/censor.ts, src/cluster/dcommands/admin/farewell.ts, src/cluster/dcommands/admin/greeting.ts, src/cluster/dcommands/admin/interval.ts, src/cluster/dcommands/admin/roleme.ts, src/cluster/dcommands/general/tag.ts
Fixes [Is there any way to escape ` character?](https://discord.com/channels/194232473931087872/1024320498286473216)
=> Show bbtag raw in codeblock if it only contains single backticks

src/api/routes/domains.ts
Needed to allow the website to display the domains list
[domains page missing](https://discord.com/channels/194232473931087872/1025773686327877772)
=> Add domains API route

src/bbtag/Subtag.ts, src/bbtag/compilation/ConditionalSubtagHandler.ts, src/bbtag/compilation/SubtagSignatureCallable.ts, src/bbtag/compilation/SubtagSignatureCallableOptions.ts, src/bbtag/compilation/compileSignatures.ts, src/bbtag/compilation/parseDefinitions.ts, src/bbtag/subtags/misc/operator.ts, src/bbtag/text.ts, src/bbtag/utils/operators.ts, src/res/i18n/en/bbtag.json, test/bbtag/subtags/misc/operator.test.ts, test/bbtag/text.test.ts
Adds subtag operator requested here: [Null coalesce operator](https://discord.com/channels/194232473931087872/1036967327264157716)
=> Add coalesce operator

src/cluster/text.ts, src/core/formatting/tag.ts, test/cluster/text.test.ts
Fixes [Date showing incorrectly](https://discord.com/channels/194232473931087872/1037790295259095091)
Timestamps need to be converted to unix time before being put into a tag
=> Fix user timestamps

src/bbtag/BBTagContext.ts, src/bbtag/BBTagUtilities.ts, src/bbtag/subtags/message/send.ts, src/bbtag/utils/debugOutput.ts, test/bbtag/subtags/message/output.test.ts, test/bbtag/subtags/message/send.test.ts
This is a continuation of #430 to fix the cases I missed
Fixes [{file} doesn't upload anything](https://discord.com/channels/194232473931087872/1040439353278734479)
=> files to file

src/bbtag/BBTagUtilities.ts, src/bbtag/subtags/guild/guildBans.ts, src/cluster/ClusterBBTagUtilities.ts, src/cluster/managers/moderation/BanManager.ts, src/core/BaseUtilities.ts, test/bbtag/subtags/guild/guildBans.test.ts
Fixes [{guildbans} still only shows the first 1,000 bans](https://discord.com/channels/194232473931087872/1040950212870549635)
=> Add support for paged bans

src/bbtag/subtags/bot/request.ts
Previously you would get an internal server error, this is much more user friendly.
Fixes [request subtag breaks when given a video URL](https://discord.com/channels/194232473931087872/1048010473523658782)
=> Add message for content length limit
