- src/tags/webhook.js
Added support for multi embeds
`{webhook;id;token;content;embeds}` where embeds can be an array of objects `[{embed1},{embed2}]`
> Tweak to webhook tag

- src/backend/helpers.js
Some subtags contain long unbroken chains of text, causing the page to become wider. When the page is too wide, the sidebar doesnt auto hide any more.
Adding zws's to break up words fixes this
> Fix tags page being too wide

- src/core/bbtag.js
- src/dcommands/ccommand.js
- src/dcommands/tag.js
- src/dcommands/timers.js
- src/structures/bbtag/Context.js
- src/structures/bbtag/Engine.js
- src/tags/lang.js
- src/utils/database.js
- Replaced by `b!t/cc setlang <tag> <lang>`
- Natively sends an embed if the content contains "/`{3}/" or is > 2000 characters
- `b!t test` wasnt escaping mentions
- Now using `Array.from` to work out the length of usernames
- When using `b!t/cc create/edit/set` if there are any unknown or unnamed subtags then errors will be shown. If there are any dynamic subtags or deprecated subtags then warnings will be shown
> Bbtag fixes & General improvements

- src/tags/color.js
This fixes an issue where {color;{color;4B8F56;hsl};hex;hsl} wouldn't work as '4B8F56' converted to HSL wasn't returning an integer, while {color;XXXXX;hex;hsl} expected an integer. The input method hsl now supports floating numbers or whatever they're called. Not like anyone is going to read this commit... right?
> Improve HSL support for {color} tag

- src/dcommands/ccommand.js
- src/dcommands/tag.js
Thanks to Neila#9580 for pointing out the box wasn't displayed when using the appropriate subcommand ´vtest´.
> Fixing the check statement for the "markdown box"

- src/dcommands/autoresponse.js
- src/dcommands/censor.js
- src/tags/regexmatch.js
- src/tags/regexreplace.js
- src/tags/regexsplit.js
- src/tags/regextest.js
- src/utils/generic.js
This PR proposes the removal of an apparently spurious unsafe regex check, that should be already covered by the library call which follows with less false positives, and updates the documentation of the commands and tags which use `bu.createRegExp` to indicate that regexes will be checked against safety and length.
I did this PR in a bit of a rush from my web browser. I think it should work, as it is a simple check removal and string modification, but perhaps I missed something or I did something essentially wrong, so I'm open to changes.
Resolves #159.
> Tweak unsafe regex detection and mention it in the docs

- src/events/ready.js
See: https://www.grammarly.com/blog/happy-new-year-2/
> Remove "'s" to Happy New Year.

- src/dcommands/modlog.js
Fixes #194 
_:warning: Beware that the bot needs the "Manage Messages" permission in order to do so!_
> Fix issue where clearing all cases wouldn't work

- src/utils/generic.js
Added UserID to the user get list
these days we need UserID's too. To use it directly with other bots that only support UserID's, very useful to get bots or get their userid very fast.
If you think, you can use the user discrimination with blargbot, yeah but, probably not sure haven't tested it but I use another bot that logs infractions and it only supports UserID's. Also this is not bad to list UserID's to directly report them.
Please add it
https://airtable.com/shrEUdEv4NM04Wi7O/tblyFuWE6fEAbaOfo/viwDg5WovcwMA9NIL/recXjAjG3xzMaQbmd?blocks=bipip3uBZFRPcSy3C
should this be added, then please build it
> Added UserID to the user get list

- src/dcommands/names.js
- src/utils/generic.js
Currently it is not possible to delete/remove usernames from the database. I updated the command to allow users to delete this data by themselves.
The main reason for this to be implemented is to resolve privacy issues mentioned [here](https://discordapp.com/channels/194232473931087872/238131984017260546/719478282525081620)
**Added:**
- -r/--remove flag in `b!names` that removes all username records in the db [
9408c3e](https://github.com/blargbot/blargbot/commit/9408c3ed1b76e05f7785fad17175804c252684e6)
> Added flag so users are able to remove usernames from b!names

- src/tags/jsonkeys.js
- src/tags/jsonsort.js
- src/tags/jsonvalues.js
Allow users to access values and keys of objects programmatically with `jsonkeys` and `jsonvalues`. Implementation-wise, this is no different from `{json}` or `{jsonget}` (code is practically indifferent), but it returns (obviously) the values or keys of the object instead.
Also implemented `jsonsort` which sorts an array of objects based on properties in the objects.
**Added:**
- `jsonvalues` and `jsonkeys` [d7ae7f8](https://github.com/blargbot/blargbot/commit/d7ae7f82c2895d776a59025497e791a15872bd88)
- `jsonsort` [ab5c5e0](https://github.com/blargbot/blargbot/pull/222/commits/ab5c5e03288a80fe9e31ca9cbfd47b3ff578e013)
> JSON extensions

- src/core/bbtag.js
- src/tags/map.js
Created a map subtag that maps the input array and either returns the output array, or modifies the original array if a variable is provided. 
I'm still not sure if the limits are appropriate, currently `map` has the same limits as `foreach`, as code-wise they're very similar.
**Added**:
- Map subtag [693c1b0](https://github.com/blargbot/blargbot/commit/693c1b021751b28883712bbe297d1e76bf53ee54)
- Map limits [57c44fa](https://github.com/blargbot/blargbot/commit/57c44fab88072dc473ef2b91bb9392ecf1429d6d)
> New map subtag for arrays

- src/tags/send.js
- src/tags/webhook.js
`webhook` currently doesn't handle base64 text inside `file`, while other subtags with the `file` parameter do. This should really be made universal, and thus I extended webhook with it. 
Also added documentation for buffer: inside `webhook` and `send`, as currently only the `file` subtag mentions `buffer:`.
**Added**:
- buffer: functionality and documenation in webhook [7757737](https://github.com/blargbot/blargbot/commit/77577372f2d8fee2eb31699809413548c561b35a)
- Documentation of buffer: in `send` [27b40a5](https://github.com/blargbot/blargbot/commit/27b40a5e0fc82e0a41c45b0496beea8ac7b02e99)
> Added buffer functionality for webhook

- src/events/messageCreate.js
Sorts prefixes based on the length instead of `a.length < b.length`, this is done in descending order so in cases where a user has a blank prefix `""` it would always pick that one and render other prefixes practically useless (as blargbot tries to execute a command with the blank prefix)
In response to suggestion [689](https://airtable.com/shrEUdEv4NM04Wi7O/tblyFuWE6fEAbaOfo/viwWwUA753iEQqOo7/recsAvekO5oAM2YVQ?blocks=bipip3uBZFRPcSy3C)
**Changed:**
- Sorting function from `a.length < b.length` to `b.length - a.length` [a247b95](https://github.com/blargbot/blargbot/commit/a247b953db088f6a26b903163032912f5208d99c)
> Sort prefixes with longer prefixes first

- src/events/messageCreate.js
As of Eris 14.0.0 they replace mentions with ` @' + '\u200b' + username` (changed in commit [13390b9](https://github.com/abalabahaha/eris/commit/13390b9b5328f57173b4a6ae4b2487ead9f1f386 "Escape more cleanContent mentions")). Since blargbot isn't checking for the zws character in the regex, the mention doesn't get stripped and results in random responses instead of the usual "Hi. My name is blargbot..." `
Examples: 
**Added**:
- `\u200b` to the Regex `Regexp('@' + username + ',?')/` [e8df93e](https://github.com/blargbot/blargbot/commit/e8df93ecc46cbe9ec31735abb68a7c1e9c86db85 "Add zws to stripped mention cleverbot")
> Add zws character so blarg strips the beginning mention in cleverbot

- src/events/messageCreate.js
Replace \<br\> with newlines.
In response to bug [687](https://airtable.com/shrEUdEv4NM04Wi7O/tblyFuWE6fEAbaOfo/viwjCMIsqe4FYzPlu/recYWDB09niUWwrHs?blocks=bipip3uBZFRPcSy3C)
**Added**:
- replacement method of br [0aead96](https://github.com/blargbot/blargbot/commit/0aead96bda11e8ad2f4f7e8dc8be6fc3e9f339b8)
> Replace br with newlines

- src/tags/channeltype.js
This adds the (relatively) new channeltypes `news` and `store` to `{channeltype}`.
**Added**:
- News and store channeltype [f2feb64](https://github.com/blargbot/blargbot/commit/f2feb64aa74ef77df7d1c2604d3bd2b305880d45)
> Support news and store channels in channeltype

- src/tags/filter.js
Fixes bug report [595](https://airtable.com/shrEUdEv4NM04Wi7O/tblyFuWE6fEAbaOfo/viwDg5WovcwMA9NIL/recTKg4fJgYCobLIb?blocks=bipip3uBZFRPcSy3C)
To avoid storing objects in the `processed` object as `[object Object]`, they need to be stringified when checking if it's processed, when storing them and when pushing equal objects to `result`.
> Fixed issue with filter and arrays with objects

- src/tags/rolecreate.js
- src/tags/rolesetperms.js
`{rolecreate}` and `{rolesetperms}` seem to be returning `Internal server occurred`  every single time and from my testings it seems to be because of the error `Cannot mix BigInt and other types, use explicit conversions` on https://github.com/blargbot/blargbot/blob/4d9d40a65efbf5986c073abd101d410bdb0645ff/src/tags/rolecreate.js#L50 and https://github.com/blargbot/blargbot/blob/4d9d40a65efbf5986c073abd101d410bdb0645ff/src/tags/rolesetperms.js#L38
Because these are internal errors I can only try to guess what's going wrong on blarg, but I'm fairly certain that this is the reason of the internal server error
**Changed**:
- Convert `options.permissions` to BigInt [4a2b8a7](https://github.com/blargbot/blargbot/commit/4a2b8a76dcbe7d6d4704161cf759ed43da8ae5ac)
- Convert `perms` to BigInt …
> Possible fix for internal errors coming from rolecreate and rolesetperms

- src/tags/exec.js
- src/tags/execcc.js
Changed `exec` and `execcc` to allow usage of flag names if they've been added. 
**Example:**
`tag1` with `b!t flag add tag1 -f flag`:
```csharp
{flagset;f}
```
`tag2`
```csharp
{exec;tag1;{args}}
```
`b!t tag2 --flag` returns `true`
Current behaviour is seen in the screenshot below
I also added a comment to a piece of code that can be removed, as mentioned in the comment itself.
**Added:**
- `flags` parameter to the `execTag` method in `{exec}`
- `.flags` value as argument in `{exec}` and `{execcc}` [8f6f179](https://github.com/blargbot/blargbot/commit/8f6f17981dbc168c6283f0122a0280316a0bc4a5)
> Added support for flag names in exec and execcc

- src/backend/main.js
Something that personally annoys me is the fact I have to authorize blarg every day or so when using the tag IDE.
I'd like to see `prompt : 'none'` added to the [strategy used](https://github.com/blargbot/blargbot/blob/4d9d40a65efbf5986c073abd101d410bdb0645ff/src/backend/main.js#L60-L64) to allow for quicker authorization.
The `prompt : 'none'` is documented under [Authorization Code Grant](https://discord.com/developers/docs/topics/oauth2#authorization-code-grant).
> Skip through the authorization screen if previously authorized

- src/dcommands/slowmode.js
Defined `channel` as the Channel Object instead of the ID. 
This was probably looked over in commit [3fb692f](https://github.com/blargbot/blargbot/commit/3fb692ff2a01a13ca48bdaa5eaa76f50cd1d5d26) where `channel` was the ID.
> Fixed bug inside slowmode

- src/tags/isuserboosting.js
- src/tags/userboostdate.js
**Added** two new subtags related to guild boosting:
- `{userboostdate;[format];[user];[quiet]}` displays the date a user started boosting a guild
- `{isuserboosting;[user];[quiet]}` returns a boolean
> Boost subtags added

- src/tags/escapebbtag.js
New subtag `escapebbtag` with alias `escape`. This would provide an easy way of escaping BBtag code, without needing to use `{rb}`, `{lb}` and `{semi}`. This could be useful if you want to set a variable to something that you don't want to parse as BBtag when setting it (without using character escape subtags).
Based on the following suggestions: [582](https://airtable.com/shrEUdEv4NM04Wi7O/tblyFuWE6fEAbaOfo/viwl0N62QIReJLMJv/reckvBdm7skJUgIUp), [549](https://airtable.com/shrEUdEv4NM04Wi7O/tblyFuWE6fEAbaOfo/viwl0N62QIReJLMJv/recGmj25ttQWk3VE3), [532](https://airtable.com/shrEUdEv4NM04Wi7O/tblyFuWE6fEAbaOfo/viwl0N62QIReJLMJv/recoukHUHMAm2dKa5), [160](https://airtable.com/shrEUdEv4NM04Wi7O/tblyFuWE6fEAbaOfo/viwl0N62QIReJLMJv/recjGBMJP02gWH0vf)
**Added**:
- escapebbtag subtag …
> New escapebbtag subtag

- src/utils/generic.js
Fixes #205 
Inside `bu.hasPerm()` there is no `return Boolean` statement if the `perm` array doesn't contain a rolename, it does check and pushes roleID's to the `role` array, but it doesn't actually return anything.
This results in users not being able to provide role ID's/mentions to command requirements, as they won't return `true` inside `bu.hasPerm()`
**Added:**
- `return` statement before the boolean [31f3f41](https://github.com/blargbot/blargbot/commit/31f3f41c571a787e733955677ca9fcb8183a7f75)
> Fixed .hasPerm() not working with roleID

- src/dcommands/time.js
- src/dcommands/timezone.js
- src/tags/usertimezone.js
**Fixed:**
- `Error: Moment Timezone has no data for ...` in `dcommands/time.js` and `dcommands/timezone.js`
- `Cannot read property 'timezone' of null`
The last fix is purely to prevent the internal error from happening. `bu.processUser` could be used to insert the user into the database, and *then* return `UTC`, but that doesn't really seem necessary.
> Fix timezone errors

- src/tags/exec.js
- src/tags/execcc.js
- Edit `{exec}` subtag to add `tag_` prefix when adding a public tag to the context cache ([f895bfd](https://github.com/blargbot/blargbot/commit/f895bfdd63a678b37c6ad883152d3f544a67245d))
- Edit `{execcc}` subtag to add `cc_` prefix when adding a ccommand to the context cache ([1b0abe7](https://github.com/blargbot/blargbot/commit/1b0abe7beef07b833b1ff3cdbac33163c5139d70))
Both to prevent conflicts when custom commands and public tags are using each other and encounter a `getCached` conflict.
An example of this issue would be the **colorme** cc calling the **colourme** cc which contains `{exec;colourme;{args}}`. What happens when **colorme** is executed:
- it adds the **colourme** ccommand to the context's cache,
- it checks for the **colourme** cached value, finds one (which is the …
> Add prefix to ccommands and tags when added to the context cache to prevent conflicts

- src/dcommands/ccommand.js
- src/utils/database.js
Add a way for cc's owner to change the authorizer of the custom command with just a subcommand.
> Add subcommand "setauthorizer" to claim authorizer role of a ccommand

- src/tags/jsonset.js
**Changed**: 
- `{jsonset}` now allows usage with only 2 arguments like `{jset;~json;key}`, which sets `key` to `undefined` and thus removes it from the JSON object
> Allow users to delete json keys with jsonset

- src/tags/lock.js
- src/utils/tag.js
**Fixed**:
- `Internal server error: TypeError Cannot read property 'id' of undefined` in `getLock` of the author scope ([sentry](https://sentry.blargbot.xyz/organizations/blargbot/issues/269/?query=lock&statsPeriod=14d))
- Server scope not being server-specific.
- Local scope not being server-specific. 
Fixes [#563](https://airtable.com/shrEUdEv4NM04Wi7O/tblyFuWE6fEAbaOfo/viwDg5WovcwMA9NIL/recTshvjPnTbuiL8o?blocks=hide) on airtable
> Fixes errors in {lock}

- src/dcommands/tag.js
**Fixed:**
- ([7e9d0bc](https://github.com/blargbot/blargbot/commit/7e9d0bcc25280d6ac58946292628d8fbed23b7c2)) `TypeError: Cannot read property 'username' of null` ([Sentry error](https://sentry.blargbot.xyz/organizations/blargbot/issues/203/?project=2&query=is%3Aunresolved&statsPeriod=14d))
When a user is not stored in rethink, their name + discrim will be `unknown user` instead of giving an error internally (and outputting nothing). 
This fixes `b!t top` and `b!t author|info <some tag whose author isn't stored anymore>`. 
- ([243ca56](https://github.com/blargbot/blargbot/commit/243ca567d09ab4d7c281651a1f2d34db7b6a87bb)) Duplicate test subcommand in `b!t help`, fixes [#737](https://airtable.com/shrEUdEv4NM04Wi7O/tblyFuWE6fEAbaOfo/viwjCMIsqe4FYzPlu/recBYetfiPakrQb6W?blocks=bipip3uBZFRPcSy3 …
> Return unknown user if author isnt stored

- src/tags/apply.js
Because `Builder.util.flattenArgArrays` can return an array with elements that are not just strings, the check inside `bbtag/Tag.js`: https://github.com/blargbot/blargbot/blob/65970bf6ad8d7be41f9cf3cc516f029dbe752c6c/src/structures/bbtag/Tag.js#L57-L62
sets `source` to `undefined`, which results in `Cannot read property 'slice' of undefined` ([sentry](https://sentry.blargbot.xyz/organizations/blargbot/issues/276/?query=is%3Aunresolved)).
Fixes airtable reports: [#340](https://airtable.com/tblyFuWE6fEAbaOfo/viwjCMIsqe4FYzPlu/rec6UGuhAnV9bLLD8?blocks=hide) and [#226](https://airtable.com/tblyFuWE6fEAbaOfo/viwjCMIsqe4FYzPlu/rec0jD8AFb6znqiem?blocks=hide)
**Changed:**
- Stringify every element in `tagArgs`.
> Fixed Internal server error in {apply}

- src/tags/channelcategory.js
- src/tags/channeldelete.js
- src/tags/channeledit.js
- src/tags/channelid.js
- src/tags/channeliscategory.js
- src/tags/channelisnsfw.js
- src/tags/channelistext.js
- src/tags/channelisvoice.js
- src/tags/channelname.js
- src/tags/channelpos.js
- src/tags/channelsetperms.js
- src/tags/channelsetpos.js
Allow users to suppress the "No channels found" output from the lookup system, because of [this discussion](https://discord.com/channels/194232473931087872/238131984017260546/855639759347122186)
**Added:**
- Pass on `context.scope.suppressLookup` to channel lookups
> Added suppresslookup for channel subtags

- src/tags/isuserboosting.js
- src/tags/roles.js
- src/tags/userboostdate.js
- src/tags/userjoinedat.js
- src/tags/usernick.js
- src/tags/userroles.js
- src/tags/userstatus.js
Added separate `0` argument handler for subtags where it defaults to the user executing the command/tag. This doesn't change anything in situations where the member is still in the guild, but for `farewell` it does.
Example where a user nicked `Custom nickname` leaves (where blargnot has the changes in this PR):
Stems from discord issue where `{usernick}` didn't work in farewells:
**Changed**:
- subtags with member defaults to use `context.member` and not the `context.guild.members` cache
> Set member to context.member where possible

- package.json
Seems like it would be a good idea to update this package to `13.1.0`, a lot of emojis have been added o/
[list of releases after 11.0.1](https://github.com/twitter/twemoji/releases?after=v11.0.1)
> Bumped twemoji to 13.1.0

- src/tags/time.js
In my opinion, `{time}` should be returning the time specified in timezone `fromTimezone` if `[time]` is empty and `[toTimezone]` is omitted. This is identical to the behaviour before `toTimezone`. My reasoning for it was that right now `bu.parseTime` will always return the 'current' time when `[time]` is empty, and then it'll just return the UTC time regardless of `[fromTimezone]`.
This kind of fixes an oversight made (by me) in the update with `toTimezone`.
This also fixes `An internal server error has occurred` when `[toTimezone]` is provided, but left empty.
**Breaking changes:**
- Returns timezone in provided `[fromTimezone]` if if `[time]` is empty and `[toTimezone]` is omitted, instead of the UTC time.
- Returns the time parsed from `[fromTimezone]` to an empty `[toTimezone]` …
> Pair of patches to {time}

- src/tags/embedbuild.js
https://discord.com/developers/docs/resources/channel#embed-limits states the description size limit is now `4096` instead of `2048`. It seems like the description length is checking in `{embedbuild}` only.
> Increased embed description limit to 4096

- src/tags/rolemention.js
- src/tags/usermention.js
Following from [support discussion](https://discord.com/channels/194232473931087872/238131984017260546/860912164910923796)
As seen in this PR, the allowed argument for `[noPing]` must be a `boolean`, unlike for example `[quiet]`. Eventually imo all parameters with 'toggle behaviour' should accept booleans only (or maybe a mix of boolean/truthy)
> Ability to toggle pings with mention subtags added

- src/tags/jsonkeys.js
- src/tags/jsonvalues.js
- src/tags/messageembeds.js
There was an issue in the examples of `messageembeds` and `jvalues` tags.
> Fixed 2 issues with docs

- src/events/messageCreate.js
Seeing as the command timeout isn't really documented anywhere, I added some more info to the 'timeout message'.
**NOTE**: I also noticed that the `penalty` variable is unused (kept it that way), but it might be good to keep this in mind in case the penalty gets modified in the future.
> Added more transparent information regarding timeouts

- src/dcommands/help.js
This doesn't entirely fix the issue when the `b!help` embed (or other embeds for that matter) is exceeds the limits, but it should give some space for more custom commands.
Ultimately something similar to `blargbot.xyz/output` should be created for embeds too, while keeping the visual aspect somewhat intact
**Changed**:
- `b!help`'s embed will now have more fields for custom commands, when they exceed the `1024` character limit.
**Discord discussion**
> Split the custom commands category in sections

- src/tags/apply.js
This PR was at first to allow the use of `{apply}` on `{function}`s, but this also happens to fix issues where users could use `{apply}` to 'bypass' context.overrides:
- `{apply}` can be used inside `{lock}` to nest them
- `{apply}` can be used inside `{filter}`/`{waitreaction}`/`{waitmessage}` to use disabled subtags.
This PR fixes these issues, and adds as mentioned before `func.name` functionality.
This also allows `apply` to execute subtags like `{reactuser}`/`{reaction}`/`{params}`/`{paramsarray}`/`{paramslength}`.
> Add context overrides to apply

- src/tags/json.js
Small QOL change for `{json}`. It feels better to use `{json}`/`{j}` than `{json;{}}`/`{j;{}}`
**Changed**:
- `input` is now optional
> Allow calling {json} without arguments for empty an json

- src/tags/tagauthor.js
- src/tags/tagauthorizer.js
Some very simple subtags to return the `author` and `authorizer` of the executing tag/cc.
With aliases `ccauthor` and `ccauthorizer` to prevent confusion regarding tags and CCs.
Stems from discord question:
**Added:**
- `{tagauthor}` and `{tagauthorizer}`
> Added tagauthor and authorizer subtags

- src/dcommands/ban.js
- src/dcommands/mute.js
- src/dcommands/remind.js
- src/dcommands/time.js
- src/dcommands/timer.js
- src/events/guildMemberAdd.js
- src/structures/bbtag/Engine.js
In this pull request I aimed to replace `moment().humanize()` to discord Timestamp that prevents blargbot to calculate humanized time and these also **Dynamic** with time in discord UI. This is how they look:
> Implementing discord Timestamps

- src/dcommands/log.js
Added support for ignoring webhooks in `b!log`. This silently fails if blarg doesn't have the `Manage Webhooks` permission.
**Added:**
- Additional check for webhooks in `b!log`
The initial suggestion mentioned including webhooks in user parsing (like bu.getUser), but I fear that might break stuff that relies on user-specific fields. So I added basic support for `b!log` only.
> Allow ignoring of webhooks if a valid webhook ID is provided

- src/dcommands/autoresponse.js
This moves the `autoresponse.list` check inside the remove block for regular autoresponses. As you will not be able to remove the everything ar if the guild has no regular autoreponses rn. 
A practically identical change has been done for the `edit` sub-command, which is not really necessary ig.
Stems from: https://discord.com/channels/194232473931087872/238131984017260546/884512653878386690
> Fixed everything ar remove/edit logic

- src/dcommands/ban.js
- src/dcommands/kick.js
- src/tags/kick.js
~~This should (I hope) fix void not supressing kick errors by changing the way they're handled from old switch to something similar to how ban subtag's errors are handled.~~
This pull request is supposed to change the architecture of ban and kick tag and default command. Both of them used completely different logic making it confusing. They are now both made in the better way (taken from ban tag and dcommand). This PR also contains other improvements, e. g. adding better replies to the commands.
**Change Log**
- Changed variable initialization system to use newer `let` instead of old `var`
- Changed variable names in kick dcommand & tag to make them same as in ban dcommand and tag
- Changed return types & values in kick command replacing numbers reprising the state with strings explaining …
> Changing architecture of kick & ban dcommand and tag

- src/backend/routes/output.js
Added `style`, `title` and `data-tooltip` to the whitelisted attributes for the output page. I went through the attribute list to see if there are perhaps more attributes blarg could support, but I didn't really find anything 'worth' adding.
**Added:**
- `style`, `title` and `data-tooltip` to the global attribute whitelist.
Stems from a feature request in `#bb-support`:
> Added more attributes to the xss whitelist

- src/events/messageCreate.js
- src/structures/bbtag/Context.js
Fixes `context.makeChild()` not using `this.authorizer` of the 'parent' context, and adds the `authorizer` option to autoresponses in case they are different.
Fixes AT bug report [#758](https://blargbot.xyz/feedback/rec7DzGDoiYRKH7kG)
**Changed:**
- `options.authorizer` is now set to `this.authorizer` in `context.makeChild()`
- autoresponses now respect differing author + authorizer [ae6acfd](https://github.com/blargbot/blargbot/commit/ae6acfdfbfc11506469ae52fd234b7cab2407bb6)
Additional context:
> Fixes custom authorizer being ignored in ars and {exec/cc}

- src/dcommands/settings.js
- src/utils/generic.js
When a member is warned and they already have a count that is equal or greater than the kickat limit, the user is still kicked. 
If you want to handle this specific behavior, you now have two choices: 
- either keep the default one, which is to kick if the user's warning counts is in the bounds [kickat, banat]
- change to the new one, which is to kick only when the user's warning counts is equal to the kickat value or when the user reaches or exceeds the kickat value for the first warning
___
- New guild setting "actonlimitsonly" (boolean value)
- Behavior when issuing a warning
Fixes #300
> Feature: add new setting not to kick when out of the limit

- src/dcommands/define.js
The words API moved hosts from mashape to rapidapi a long time ago, but blarg never updated.
New docs: https://rapidapi.com/dpventures/api/wordsapi/
> Switch to the rapidapi host rather than mashape

- src/core/Metrics.js
- src/structures/TagBuilder.js
As blargbot appears to be suffering from increased latency a bit more than usual, I figured it'd perhaps be useful to have a way of viewing the execution rate of (specific) subtags which would be possible with a simple prometheus counter.
**PS**: This change will require the master process to be restarted
> Added subtag counter to metrics

- src/structures/bbtag/Context.js
As `Context.serialize` now uses `bu.getMessage` instead of `bot.getMessage`, in cases when the original input message doesn't exist anymore it now doesn't throw an error for the `catch` to handle.
Fixes oversight made in commit [5f6af5d](https://github.com/blargbot/blargbot/commit/5f6af5dcf4577d9e73b6ee72ad505f2eb5514700)
> Fix unknown message not being handled

- src/utils/generic.js
This fixes [airtable report #773](https://airtable.com/shrEUdEv4NM04Wi7O/tblyFuWE6fEAbaOfo/viwDg5WovcwMA9NIL/recDeTcTHyazvXh1W?blocks=bipip3uBZFRPcSy3C)
> Fix wrong syntax usage in bu.getMessage

- src/tags/exec.js
- src/tags/execcc.js
This fixes an issue where back slashes were being lost when using exec(cc) because they were being removed and not added back.
> Fix exec and execcc

- src/structures/bbtag/Context.js
- src/tags/send.js
- src/tags/webhook.js
The webhook subtag doesnt respect the allowed mentions list, causing it to never send any mentions. This makes it use the same list as output and send
> Add allowed mentions to webhook payload

- src/bbtag/subtags/message/waitmessage.ts
- src/bbtag/subtags/message/waitreaction.ts
- src/bbtag/utils/json.ts
- src/cluster/dcommands/general/define.ts
- src/cluster/managers/awaiters/Awaiter.ts
- test/bbtag/subtags/message/waitmessage.test.ts
- test/bbtag/subtags/message/waitreaction.test.ts
- Regression fix for {waitreact} and {waitmessage}.
- if the condition doesnt return `true` or `false`, an error should be thrown. [Old code](https://github.com/blargbot/blargbot/blob/1189d139610f51e9fec1c19871f821fc166d238d/src/tags/waitmessage.js#L146-L150)
- Regression fix for {jget;~var;}
- In js blarg this used to get the `""` property (empty key). 
- Fix for define command not working
- Api response structure added new props but the parser was strict so rejected the payload
> Misc fixes

- src/cluster/dcommands/general/emoji.ts
emoji command sometimes fails, for instance with ⏲️, because it includes a `variation selector-16` character which needs to be stripped from the codepoint to be able to find the file in twemoji. sometimes.
> Ignore variation selector if present

- src/bbtag/BBTagContext.ts
- src/bbtag/types.ts
Embeds and files set before starting a timer would be sent again by the timer
- Old blarg would ignore some of the `data` (previously `state`) of the context in a timer. [Evidence](https://github.com/blargbot/blargbot/blob/1189d139610f51e9fec1c19871f821fc166d238d/src/dcommands/tag.js#L829-L913)
> Dont persist bbcontext data through timer

- src/bbtag/subtags/user/userboostdate.ts
- test/bbtag/subtags/user/userboostdate.test.ts
This offsets the moment to utc 0, just like it was on blarg-js.
This also fixes wrong example docs for `{userboosdate;<format>;<user>;[quiet]}` and fixes a classname typo
> Fix UTC+0 offset not being applied in {userboostdate}

- src/cluster/managers/AutoresponseManager.ts
- src/core/utils/guard/matchMessageFilter.ts
Fixes an [autoresponse Issue](https://discord.com/channels/194232473931087872/988044656665325600) where argslength is always 1
[Duplicate report](https://discord.com/channels/194232473931087872/988457883626795009)
> Autoresponse only uses captures if > 0

- src/cluster/managers/moderation/EventLogManager.ts
Iso-functional fix: add back a description for the nameupdate
> fix: add description to embed

- src/core/utils/parse/flags.ts
A flag is only a flag if it isnt preceded by a \ or a "
Fixes [backslash not working](https://discord.com/channels/194232473931087872/995326420324728882)
> Flag parsing should respect escapes

- src/core/utils/parse/flags.ts
- test/bbtag/subtags/bot/exec.test.ts
- test/bbtag/subtags/bot/execcc.test.ts
Fixes [flags broken inside of '{exec}' when arguments passed before them](https://discord.com/channels/194232473931087872/997769937865150534)
> Fix flags in exec(cc)

- src/core/serviceTypes/WorkerPoolEventService.ts
- src/core/worker/WorkerPool.ts
- src/master/events/cluster/clusterStats.ts
- src/master/managers/ClusterStatsManager.ts
- src/master/services/ClusterMonitor.ts
Improves the logging for when a cluster dies, and reduces how often a double respawn will happen.
This is a change to the master process, so will need a `b!respawn kill` to deploy
> Fix incorrect message from unresponsive cluster & reduce double respawn risk

- src/bbtag/limits/CustomCommandLimit.ts
- src/bbtag/limits/EverythingAutoResponseLimit.ts
- src/bbtag/limits/GeneralAutoResponseLimit.ts
- src/bbtag/limits/GlobalLimit.ts
- src/bbtag/limits/TagLimit.ts
- src/cluster/events/discord/guildMemberUpdate.ts
- src/logger/test.ts
An issue with the docs in eris caused incorrect modlog entries to be fired, and we missed the usage restrictions for timeout.
> Fix timeout modlog and restrictions

- src/bbtag/subtags/role/roleadd.ts
- src/bbtag/subtags/role/roleremove.ts
- src/bbtag/subtags/user/usersetnick.ts
- src/bbtag/subtags/user/usersetroles.ts
- src/cluster/dcommands/general/decancer.ts
- src/cluster/managers/RolemeManager.ts
It would seem that calling `Member#edit` doesnt cause eris to ensure the member is edited before resolving the promise. I think this is causing a race condition in some situations. This PR hopefully fixes [Something screwy going on with {jget} or {roleadd} and {roleremove}](https://discord.com/channels/194232473931087872/1012147398333706363) but will need testing once deployed to be sure
> Potentially fix member edit race condition

- src/cluster/managers/documentation/DocumentationTreeManager.ts
Fixes an issue I noticed when doing `b!t docs json`
> Fix documentation sort order & only show exact matches

- src/cluster/dcommands/admin/censor.ts
- src/cluster/managers/moderation/CensorManager.ts
- src/cluster/utils/constants/moderationType.ts
This is a regression from how blargbot used to work. Autoresponses also used to run regardless of the message being censored, but now they dont. Im choosing not to fix that as there is an easy workaround for that - {exec}
Fixes [Autoresponse and censor conflict](https://discord.com/channels/194232473931087872/1004925794860150836)
> Allow 1 message to trigger multiple censors

- src/cluster/dcommands/admin/autoresponse.ts
- src/cluster/dcommands/admin/ccommand.ts
- src/cluster/dcommands/admin/censor.ts
- src/cluster/dcommands/admin/farewell.ts
- src/cluster/dcommands/admin/greeting.ts
- src/cluster/dcommands/admin/interval.ts
- src/cluster/dcommands/admin/roleme.ts
- src/cluster/dcommands/general/tag.ts
Allows you to specify the file type for the `raw` commands when getting bbtag.
Implements [#814](https://airtable.com/appKTYe5luRw2aoas/tblyFuWE6fEAbaOfo/viwDg5WovcwMA9NIL/reczTF7VBRsv9mmAQ)
> Add extension parameter to the bbtag raw commands

- src/cluster/dcommands/admin/editcommand.ts
`b!editcommand list` was showing edits to commands globally rather than for the current guild, of which there is never any. Good job me.
Thanks [Pippy#5263](https://discord.com/users/414367180667355146) for pointing out this one!
> editcommand list needs to provide a location

- src/cluster/dcommands/general/tag.ts
Adds a confirmation message to ensure staff dont accidentally edit/delete someone elses tag.
> Add confirmation for staff editing someone elses tag

- definitions/rethinkdb/index.d.ts
- src/api/routes/guilds/ccommands.ts
- src/cluster/dcommands/admin/ccommand.ts
- src/cluster/managers/commands/CustomCommandManager.ts
- src/cluster/managers/commands/DefaultCommandManager.ts
- src/cluster/managers/documentation/CommandDocumentationManager.ts
- src/cluster/types.ts
- src/database/stores/RethinkDbGuildStore.ts
- src/domain/models/guilds/GuildCommandTagBase.ts
- test/bbtag/subtags/bot/execcc.test.ts
Fixes [b!help sends nothing when there are too many commands](https://discord.com/channels/194232473931087872/1019673077086425151)
I added a character limit on command names to prevent them from breaking the help documentation. The names get put into the label field of the dropdowns, which discord limits to 100 characters.
The migration changes are designed to be expandable in the future, and to only ever be run once. I might restructure it later to be reusable for the other tables, but at the moment only the guild table needs it.
Theres no concerns about race conditions with the migrations as a cluster/master isnt classed as ready until the database is connected which includes the migrations having been run. To be safe, we should `restart kill` to deploy this codebase however.
> Add limits on command names and handle large command counts

- src/api/routes/dumps.ts
Fixes [{dump} output link leads to a server error.](https://discord.com/channels/194232473931087872/1027125450985709578)
> Fix dumps with no embeds

- src/cluster/dcommands/admin/editcommand.ts
If editcommand has the hidden `help` subcommand, it makes it impossible to edit the help command, e.g. `b!editcommand help disable`
Fixes [Option to disable multiple commands at once broke?](https://discord.com/channels/194232473931087872/1024612610718564383)
> Disable `b!editcommand help` for convenience

- src/bbtag/text.ts
- src/cluster/dcommands/admin/settings.ts
- src/cluster/text.ts
- src/crowdin/index.ts
- test/bbtag/text.test.ts
- test/cluster/text.test.ts
This just adds the en "translation" back to the listing, which represents the default text blarg will send
> Fix translations and add fake english translation

- src/cluster/command/GlobalImageCommand.ts
- src/cluster/command/RawBBTagCommandResult.ts
- src/cluster/dcommands/admin/ccommand.ts
- src/cluster/dcommands/admin/logs.ts
- src/cluster/dcommands/developer/i18n.ts
- src/cluster/dcommands/developer/update.ts
- src/cluster/dcommands/general/avatar.ts
- src/cluster/dcommands/general/status.ts
- src/cluster/dcommands/general/tag.ts
- src/cluster/dcommands/image/cah.ts
- src/cluster/dcommands/owner/exec.ts
- src/core/BaseUtilities.ts
- src/core/types.ts
- src/master/events/cluster/exit.ts
- src/master/services/ClusterMonitor.ts
When sending files, blargbot strips off the `files` property because that is sent in a second parameter in eris. This is different for editing messages, where eris checks for a `file` property on the message payload. Dont ask why, its a bit nuts. This brings all of blargbot in line with eris, using the `file` property rather than `files`
Typing in eris:
> Use file not files

- src/crowdin/index.ts
Language names should be in the language its describing rather than english
> Add locale name from language definition
